name: sezinsoft_lint_rules
description: Lint rules for Flutter used internally at Sezinsoft BiliÅŸim Teknolojileri.
version: 0.0.1
environment:
  sdk: ">=2.19.6 <3.0.0"
dev_dependencies:
  flutter_lints: ^2.0.1